---
servers:
- url: "http://localhost:8080"
openapi: "3.0.0"
paths:
  /pet:
    $ref: "./pets-api.yml#/paths/~1pet"
  /user/{username}:
    $ref: "./pets-api.yml#/paths/~1user~1{username}"
  /pet/findByStatus:
    $ref: "./pets-api.yml#/paths/~1pet~1findByStatus"
  /user/createWithList:
    $ref: "./pets-api.yml#/paths/~1user~1createWithList"
  /pet/{petId}/uploadImage:
    $ref: "./pets-api.yml#/paths/~1pet~1{petId}~1uploadImage"
  /store/inventory:
    $ref: "./pets-api.yml#/paths/~1store~1inventory"
  /user/login:
    $ref: "./pets-api.yml#/paths/~1user~1login"
  /user:
    $ref: "./pets-api.yml#/paths/~1user"
  /user/createWithArray:
    $ref: "./pets-api.yml#/paths/~1user~1createWithArray"
  /pet/findByTags:
    $ref: "./pets-api.yml#/paths/~1pet~1findByTags"
  /store/order:
    $ref: "./pets-api.yml#/paths/~1store~1order"
  /user/logout:
    $ref: "./pets-api.yml#/paths/~1user~1logout"
  /pet/{petId}:
    $ref: "./pets-api.yml#/paths/~1pet~1{petId}"
  /store/order/{orderId}:
    $ref: "./pets-api.yml#/paths/~1store~1order~1{orderId}"
info:
  title: "merged spec"
  description: "merged spec"
  version: "1.0.0"
